### ISSUE TITLE
Home(Left menu) - Editing the Profile details with Email and Mobile values shows like it is saved. But it is not saved actually

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/Healfie-iOS#1]
## Steps To Reproduce:
1. The default profile name is added as 'Me'.
2. In the left menu, tap on the 'Me' profile image to edit the profile details
3. The Profile screen opens. Enter details for "Email" and "Mobile" values
4. click on the tick mark to save.
5. Go to any other screen (like dashboard...) and come back to the Me profile edit page.
## Actual Result:

The saved values for "Email" and "Mobile" is not retained
## Expected Result:

The values should be displayed with the previously entered values

**Comment by venkateshGaripally** [comment]
Issue #1 - Fixed.

**Comment by shanthasprim** [comment]
Can edit the Profile details now. Hence closing the issue
