### ISSUE TITLE
Profile - The Edit Profile mobile number field limit should be changed

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/Healfie-iOS#14]
## Steps To Reproduce:
1. Open the left menu
2. Tap on the profile image to edit the profile
3. The "Update Profile" screen opens.
4. Check the 'Mobile number' field
## Actual Result:

The Mobile number field is restricted to 10 digits
## Expected Result:

The mobile number should be limited to 15 digit number. Separate field to add the country code should be added.

**Comment by venkateshGaripally** [comment]
Issue #14 - Fixed

**Comment by shanthasprim** [comment]
Working as Expected. Hence closing the issue.
