### ISSUE TITLE
Healfie - Health Parameters with a scroll does not store the values unless the user clicks on the screen

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/Healfie-iOS#15]
## Steps To Reproduce:
1. Add a healfie and add the health parameters as 'Weight' and 'Stress' (or 'Food Intake' or 'Sleep' or 'Mood')
2. Enter 'weight' value as 60 and scroll 'stress' value to 4 and directly click on the tick on the right top corner of the screen to save the healfie
3. Check the newly added healfie value
## Actual Result:

The 'Weight' value alone is recorded and the 'stress' value shows 'No data to show'
## Expected Result:

The scroll value is not saved without the user clicking anywhere on the screen after scrolling for a value.
A 'Done' button can be added to avoid this confusion.

**Comment by venkateshGaripally** [comment]
Issue #15 - Fixed

**Comment by shanthasprim** [comment]
This is working as expected. Scrolling and directly saving or clicking anywhere in the screen and saving the values works.
