### ISSUE TITLE
Healfie - Entering the health parameter values and then changing the Healfie picture or Healfie Profile removes the entered health parameter values

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/Healfie-iOS#16]
## Steps To Reproduce:
1. Click on the camera icon to add a new healfie.
2. Add and Enter values for the health parameters 
3. Before saving the healfie, try changing the Profile name or the Healfie pic
## Actual Result:

The health parameter values are removed and the fields are made empty
## Expected Result:

The health parameter values should not be removed

**Comment by venkateshGaripally** [comment]
Issue #16 - Fixed.

**Comment by shanthasprim** [comment]
Working as Expected. Hence Closing the issue.
