### ISSUE TITLE
Profiles - Opening any profile from the Profiles section shows "Email" field with mobile number and "Mobile" value as empty

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/Healfie-iOS#2]
## Steps To Reproduce:
1. Tap the left menu and select "Profiles" from the left menu
2. Open any Profile value listed (see Preconditions)
3. Check the "Email" and "Mobile" values
## Actual Result:

 "Email" field is displayed with the mobile number and "Mobile" value as empty
## Expected Result:

The values should be displayed accordingly
## Precondition:

New Profile values to be added already with valid "Email" and "Mobile Number" values.

**Comment by venkateshGaripally** [comment]
Issue #2 - Fixed.

**Comment by shanthasprim** [comment]
Working as Expected. Hence closing the issue
