### ISSUE TITLE
Healfie - Health Parameter Validations

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/Healfie-iOS#3]
## Steps To Reproduce:
1. Add a healfie by clicking on the camera icon
2. Click on add health parameters and add Weight, Waist C and Fitness parameters
3. Check these fields
## Actual Result:
1. All three fields accepts indefinite value entry
## Expected Result:
1. Restrict Weight value to 5 digit limit accepting only one dot(.) to symbolize decimal point
2. Restrict Waist C value to 5 digit limit accepting only one dot(.) to symbolize decimal point
3. Restrict Fitness value to 5 digit limit accepting only one dot(.) to symbolize decimal point

**Comment by venkateshGaripally** [comment]
Issue #3 - Fixed

**Comment by shanthasprim** [comment]
Working as Expected.
