### ISSUE TITLE
Profiles - Deleting a Profile should alert the user and should delete the Healfie's under the profile

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/Healfie-iOS#4]
## Steps To Reproduce:
1. Tap on the "Profiles" from the left menu
2. click on the 'Delete' icon in the top.
3. Select and click on delete for any particular profile
## Actual Result:
1. The Profile gets deleted without any alert to the user
2. The Healfie's added under the profile does not get deleted.
## Expected Result:
1. The user should be alerted with an error message as "Deleting Profile also deletes the Respective healfie's added under it. Do u want to continue?"
2. Clicking "Yes" in the alert should delete that particular profile and Healfie's added under that Profile.
## Precondition:

New profile added and Healfie value added for that profile

**Comment by venkateshGaripally** [comment]
Issue #4 - Fixed.

**Comment by shanthasprim** [comment]
Working as Expected.
