### ISSUE TITLE
Profiles - Should accept same profile name?

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/Healfie-iOS#7]
## Steps To Reproduce:
1. Click on the left menu and select the menu items "Profiles" 
2. Click on the '+' to add new Profile.
3. Add a new profile value with the same existing profile name
## Actual Result:

The Profile name is accepted and duplicate entry of profile with the same profile name is created.
## Expected Result:

Can Profile name accept same profile name value?

**Comment by venkateshGaripally** [comment]
Issue #7- Fixed

**Comment by shanthasprim** [comment]
Working as Expected. Hence closing it.
